version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    env_file:
    - .env
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: ["npm", "start"]
    user: "1000"